/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{html,jsx,js}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Helvetica Neue", "Helvetica"],
      },
      colors: {
        light: {
          primary: "#3A86FF",
          surfaceTint: "#3A86FF",
          onPrimary: "#FFFFFF",
          primaryContainer: "#E0F2FF",
          onPrimaryContainer: "#001D4A",
          secondary: "#8338EC",
          onSecondary: "#FFFFFF",
          secondaryContainer: "#E7E0FF",
          onSecondaryContainer: "#21005D",
          tertiary: "#FB5607",
          onTertiary: "#FFFFFF",
          tertiaryContainer: "#FFE2D6",
          onTertiaryContainer: "#431100",
          error: "#FF006E",
          onError: "#FFFFFF",
          errorContainer: "#FFD6E0",
          onErrorContainer: "#400012",
          background: "#F6F7FB",
          onBackground: "#1D1D1D",
          surface: "#FFFFFF",
          onSurface: "#ffffff",
          surfaceVariant: "#E0E4E7",
          onSurfaceVariant: "#494D53",
          outline: "#ADB5BD",
          outlineVariant: "#CED4DA",
          shadow: "#000000",
          scrim: "#000000",
          inverseSurface: "#2E3440",
          inverseOnSurface: "#E6EBF1",
          inversePrimary: "#75BFFF",
          primaryFixed: "#E0F2FF",
          onPrimaryFixed: "#001D4A",
          primaryFixedDim: "#B3D9FF",
          onPrimaryFixedVariant: "#003A86",
          secondaryFixed: "#E7E0FF",
          onSecondaryFixed: "#21005D",
          secondaryFixedDim: "#D1B3FF",
          onSecondaryFixedVariant: "#5200B0",
          tertiaryFixed: "#FFE2D6",
          onTertiaryFixed: "#431100",
          tertiaryFixedDim: "#FF9673",
          onTertiaryFixedVariant: "#7F3F00",
          surfaceDim: "#F0F2F5",
          surfaceBright: "#F9FAFB",
          surfaceContainerLowest: "#FFFFFF",
          surfaceContainerLow: "#F5F6F8",
          surfaceContainer: "#EFF0F4",
          surfaceContainerHigh: "#E8EAED",
          surfaceContainerHighest: "#E2E4E7",
        },
        dark: {
          primary: "#75BFFF",
          surfaceTint: "#75BFFF",
          onPrimary: "#002A5D",
          primaryContainer: "#004B9A",
          onPrimaryContainer: "#E0F2FF",
          secondary: "#D1B3FF",
          onSecondary: "#3D006B",
          secondaryContainer: "#5200B0",
          onSecondaryContainer: "#E7E0FF",
          tertiary: "#FF9673",
          onTertiary: "#591800",
          tertiaryContainer: "#7F3F00",
          onTertiaryContainer: "#FFE2D6",
          error: "#FF739E",
          onError: "#5A0026",
          errorContainer: "#7F0035",
          onErrorContainer: "#FFD6E0",
          background: "#1A1A1A",
          onBackground: "#E6E6E6",
          surface: "#121212",
          onSurface: "#E6E6E6",
          surfaceVariant: "#343434",
          onSurfaceVariant: "#A6A6A6",
          outline: "#626262",
          outlineVariant: "#3F4945",
          shadow: "#000000",
          scrim: "#000000",
          inverseSurface: "#E6E6E6",
          inverseOnSurface: "#1A1A1A",
          inversePrimary: "#3A86FF",
          primaryFixed: "#004B9A",
          onPrimaryFixed: "#E0F2FF",
          primaryFixedDim: "#75BFFF",
          onPrimaryFixedVariant: "#002A5D",
          secondaryFixed: "#5200B0",
          onSecondaryFixed: "#E7E0FF",
          secondaryFixedDim: "#D1B3FF",
          onSecondaryFixedVariant: "#3D006B",
          tertiaryFixed: "#7F3F00",
          onTertiaryFixed: "#FFE2D6",
          tertiaryFixedDim: "#FF9673",
          onTertiaryFixedVariant: "#591800",
          surfaceDim: "#0E1513",
          surfaceBright: "#343B38",
          surfaceContainerLowest: "#090F0E",
          surfaceContainerLow: "#171D1B",
          surfaceContainer: "#1B211F",
          surfaceContainerHigh: "#252B29",
          surfaceContainerHighest: "#303634",
        },
      },
      space: {
        0: "0px",
        1: "4px",
        2: "8px",
        3: "12px",
        4: "16px",
        5: "20px",
        6: "24px",
        7: "28px",
        8: "32px",
        9: "36px",
        10: "40px",
        11: "44px",
        12: "48px",
        13: "52px",
        14: "56px",
        15: "60px",
        16: "64px",
        17: "68px",
        18: "72px",
        19: "76px",
        20: "80px",
        21: "84px",
        22: "88px",
        23: "92px",
        24: "96px",
        25: "100px",
        26: "104px",
        27: "108px",
        28: "112px",
        29: "116px",
        30: "120px",
      },
      boxShadow: {
        elevation1:
          "0px 1px 2px 0px rgba(0, 0, 0, 0.30), 0px 1px 3px 1px rgba(0, 0, 0, 0.15)",
        elevation2:
          "0px 1px 2px 0px rgba(0, 0, 0, 0.30), 0px 2px 6px 2px rgba(0, 0, 0, 0.15)",
        elevation3:
          "0px 4px 8px 3px rgba(0, 0, 0, 0.15), 0px 1px 3px 0px rgba(0, 0, 0, 0.30)",
        elevation4:
          "0px 6px 10px 4px rgba(0, 0, 0, 0.15), 0px 2px 3px 0px rgba(0, 0, 0, 0.30)",
        elevation5:
          "0px 8px 12px 6px rgba(0, 0, 0, 0.15), 0px 4px 4px 0px rgba(0, 0, 0, 0.30)",
      },
      borderRadius: {
        none: "0",
        extraSmall: "4px",
        small: "8px",
        medium: "12px",
        large: "16px",
        extraLarge: "28px",
        full: "1000px",
      },
      fontSize: {
        displayLarge: [
          "57px",
          {
            fontWeight: "400",
            lineHeight: "64px",
            letterSpacing: "-0.25px",
          },
        ],
        displayMedium: [
          "45px",
          {
            fontWeight: "400",
            lineHeight: "52px",
            letterSpacing: "0",
          },
        ],
        displaySmall: [
          "36px",
          {
            fontWeight: "400",
            lineHeight: "44px",
            letterSpacing: "0",
          },
        ],
        headlineLarge: [
          "32px",
          {
            fontWeight: "400",
            lineHeight: "40px",
            letterSpacing: "0",
          },
        ],
        headlineMedium: [
          "28px",
          {
            fontWeight: "400",
            lineHeight: "36px",
            letterSpacing: "0",
          },
        ],
        headlineSmall: [
          "24px",
          {
            fontWeight: "400",
            lineHeight: "32px",
            letterSpacing: "0",
          },
        ],
        titleLarge: [
          "22px",
          {
            fontWeight: "400",
            lineHeight: "28px",
            letterSpacing: "0",
          },
        ],
        titleMedium: [
          "16px",
          {
            fontWeight: "500",
            lineHeight: "24px",
            letterSpacing: "0.15px",
          },
        ],
        titleSmall: [
          "14px",
          {
            fontWeight: "500",
            lineHeight: "20px",
            letterSpacing: "0.1px",
          },
        ],
        bodyLarge: [
          "16px",
          {
            fontWeight: "400",
            lineHeight: "24px",
            letterSpacing: "0.5px",
          },
        ],
        bodyMedium: [
          "14px",
          {
            fontWeight: "400",
            lineHeight: "20px",
            letterSpacing: "0.25px",
          },
        ],
        bodySmall: [
          "12px",
          {
            fontWeight: "400",
            lineHeight: "16px",
            letterSpacing: "0.4px",
          },
        ],
        labelLarge: [
          "14px",
          {
            fontWeight: "500",
            lineHeight: "20px",
            letterSpacing: "0.1px",
          },
        ],
        labelMedium: [
          "12px",
          {
            fontWeight: "500",
            lineHeight: "16px",
            letterSpacing: "0.5px",
          },
        ],
        labelSmall: [
          "11px",
          {
            fontWeight: "500",
            lineHeight: "16px",
            letterSpacing: "0.5px",
          },
        ],
      },
      transitionDuration: {
        short1: "50ms",
        short2: "100ms",
        short3: "150ms",
        short4: "200ms",
        medium1: "250ms",
        medium2: "300ms",
        medium3: "350ms",
        medium4: "400ms",
        long1: "450ms",
        long2: "500ms",
        long3: "550ms",
        long4: "600ms",
        extraLong1: "700ms",
        extraLong2: "800ms",
        extraLong3: "900ms",
        extraLong4: "1000ms",
      },
      transitionDelay: {
        short1: "50ms",
        short2: "100ms",
        short3: "150ms",
        short4: "200ms",
        medium1: "250ms",
        medium2: "300ms",
        medium3: "350ms",
        medium4: "400ms",
        long1: "450ms",
        long2: "500ms",
        long3: "550ms",
        long4: "600ms",
        extraLong1: "700ms",
        extraLong2: "800ms",
        extraLong3: "900ms",
        extraLong4: "1000ms",
      },
      transitionTimingFunction: {
        standard: "cubic-bezier(0.2, 0, 0, 1)",
        standardDecelerate: "cubic-bezier(0, 0, 0, 1)",
        standardAccelerate: "cubic-bezier(0.3, 0, 1, 1)",
        emphasized: "cubic-bezier(0.2, 0, 0, 1.0)",
        emphasizedDecelerate: "cubic-bezier(0.05, 0.7, 0.1, 1)",
        emphasizedAccelerate: "cubic-bezier(0.3, 0, 0.8, 0.15)",
        legacy: "cubic-bezier(0.4, 0, 0.2, 1.0)",
        legacyDecelerate: "cubic-bezier(0, 0, 0.2, 1)",
        legacyAccelerate: "cubic-bezier(0.4, 0, 1, 1)",
        linear: "cubic-bezier(0, 0, 1, 1)",
      },
    },
  },
  plugins: [],
};
